import type { ConnectorModuleConfig } from "@/lib/connectors/shared/module-config";

export const GOOGLE_CONNECTOR_CONFIG: ConnectorModuleConfig = {
  id: "google",
  name: "Google Workspace",
  description: "Gmail, Calendar, Drive, Docs, and Google Chat.",
  category: "workspace",
  supportedActions: [
    "send_gmail",
    "create_calendar_event",
    "list_drive_files",
    "read_doc_metadata",
    "send_google_chat_message",
  ],
  supportedTriggers: ["email_received", "calendar_event_created", "drive_file_updated"],
  oauth: "oauth2_pkce",
  services: ["gmail", "calendar", "drive", "docs", "chat"],
  authEnvPrefix: "GOOGLE",
  defaultScopes: [
    "https://www.googleapis.com/auth/gmail.send",
    "https://www.googleapis.com/auth/calendar.events",
    "https://www.googleapis.com/auth/drive.metadata.readonly",
    "https://www.googleapis.com/auth/documents.readonly",
  ],
  authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
  tokenUrl: "https://oauth2.googleapis.com/token",
  apiBaseUrl: "https://www.googleapis.com",
  resourceLabel: "Workspace resources",
};

export const MICROSOFT_CONNECTOR_CONFIG: ConnectorModuleConfig = {
  id: "microsoft",
  name: "Microsoft 365",
  description: "Outlook, Teams, OneDrive, SharePoint, and Microsoft Graph.",
  category: "workspace",
  supportedActions: [
    "send_outlook_mail",
    "create_teams_message",
    "list_onedrive_files",
    "list_sharepoint_items",
    "create_calendar_event",
  ],
  supportedTriggers: ["mail_received", "teams_message", "file_updated"],
  oauth: "oauth2",
  services: ["outlook", "teams", "onedrive", "sharepoint", "graph", "entra"],
  authEnvPrefix: "MICROSOFT",
  defaultScopes: ["offline_access", "User.Read", "Mail.Send", "Calendars.ReadWrite", "Files.Read"],
  authorizeUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
  tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
  apiBaseUrl: "https://graph.microsoft.com/v1.0",
  resourceLabel: "Microsoft 365 resources",
};

export const JIRA_CONNECTOR_CONFIG: ConnectorModuleConfig = {
  id: "jira",
  name: "Jira",
  description: "Projects, issues, comments, transitions, and assignees.",
  category: "devops",
  supportedActions: ["create_jira_issue", "update_jira_issue", "transition_jira_issue", "add_jira_comment"],
  supportedTriggers: ["issue_created", "issue_updated", "issue_transitioned"],
  oauth: "oauth2",
  authEnvPrefix: "JIRA",
  defaultScopes: ["read:jira-work", "write:jira-work", "offline_access"],
  authorizeUrl: "https://auth.atlassian.com/authorize",
  tokenUrl: "https://auth.atlassian.com/oauth/token",
  apiBaseUrl: "https://api.atlassian.com",
  resourceLabel: "Jira projects",
};

export const GITHUB_CONNECTOR_CONFIG: ConnectorModuleConfig = {
  id: "github",
  name: "GitHub",
  description: "Repositories, issues, pull requests, releases, and Actions.",
  category: "devops",
  supportedActions: ["create_github_issue", "comment_github_issue", "open_github_pr_draft", "trigger_github_workflow"],
  supportedTriggers: ["push", "pull_request", "workflow_run", "release_published"],
  oauth: "oauth2",
  authEnvPrefix: "GITHUB",
  defaultScopes: ["repo", "read:org", "workflow"],
  authorizeUrl: "https://github.com/login/oauth/authorize",
  tokenUrl: "https://github.com/login/oauth/access_token",
  apiBaseUrl: "https://api.github.com",
  resourceLabel: "Repositories",
};

export const GITLAB_CONNECTOR_CONFIG: ConnectorModuleConfig = {
  id: "gitlab",
  name: "GitLab",
  description: "Projects, merge requests, issues, and pipelines.",
  category: "devops",
  supportedActions: ["create_gitlab_issue", "create_gitlab_merge_request", "list_gitlab_pipelines"],
  supportedTriggers: ["push", "merge_request", "pipeline"],
  oauth: "oauth2",
  authEnvPrefix: "GITLAB",
  defaultScopes: ["api", "read_user"],
  authorizeUrl: "https://gitlab.com/oauth/authorize",
  tokenUrl: "https://gitlab.com/oauth/token",
  apiBaseUrl: "https://gitlab.com/api/v4",
  resourceLabel: "GitLab projects",
};

export const NOTION_CONNECTOR_CONFIG: ConnectorModuleConfig = {
  id: "notion",
  name: "Notion",
  description: "Databases, pages, search, and content append.",
  category: "productivity",
  supportedActions: ["create_notion_page", "append_notion_content", "search_notion", "query_notion_database"],
  supportedTriggers: ["page_updated", "database_updated"],
  oauth: "oauth2",
  authEnvPrefix: "NOTION",
  defaultScopes: [],
  authorizeUrl: "https://api.notion.com/v1/oauth/authorize",
  tokenUrl: "https://api.notion.com/v1/oauth/token",
  apiBaseUrl: "https://api.notion.com/v1",
  resourceLabel: "Notion workspaces",
};

export const SLACK_CONNECTOR_CONFIG: ConnectorModuleConfig = {
  id: "slack",
  name: "Slack",
  description: "Native Slack connector for channels, messages, and events.",
  category: "messaging",
  supportedActions: ["send_slack_message", "list_slack_channels"],
  supportedTriggers: ["message_posted", "reaction_added"],
  oauth: "oauth2",
  authEnvPrefix: "SLACK",
  defaultScopes: ["chat:write", "channels:read", "users:read"],
  authorizeUrl: "https://slack.com/oauth/v2/authorize",
  tokenUrl: "https://slack.com/api/oauth.v2.access",
  apiBaseUrl: "https://slack.com/api",
  resourceLabel: "Slack workspaces",
};

export const TEAMS_CONNECTOR_CONFIG: ConnectorModuleConfig = {
  id: "teams",
  name: "Microsoft Teams",
  description: "Native Teams connector for channels and messages.",
  category: "messaging",
  supportedActions: ["send_teams_message", "list_teams_channels"],
  supportedTriggers: ["teams_message", "channel_created"],
  oauth: "oauth2",
  authEnvPrefix: "TEAMS",
  defaultScopes: ["ChannelMessage.Send", "Channel.ReadBasic.All"],
  authorizeUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
  tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
  apiBaseUrl: "https://graph.microsoft.com/v1.0",
  resourceLabel: "Teams channels",
};

export const LINEAR_CONNECTOR_CONFIG: ConnectorModuleConfig = {
  id: "linear",
  name: "Linear",
  description: "Issues, status, comments, and assignees.",
  category: "productivity",
  supportedActions: ["create_linear_issue", "update_linear_issue", "comment_linear_issue"],
  supportedTriggers: ["issue_created", "issue_updated"],
  oauth: "oauth2",
  authEnvPrefix: "LINEAR",
  defaultScopes: ["read", "write", "issues:create"],
  authorizeUrl: "https://linear.app/oauth/authorize",
  tokenUrl: "https://api.linear.app/oauth/token",
  apiBaseUrl: "https://api.linear.app",
  resourceLabel: "Linear teams",
};

export const HUBSPOT_CONNECTOR_CONFIG: ConnectorModuleConfig = {
  id: "hubspot",
  name: "HubSpot",
  description: "CRM contacts, companies, deals, and activities.",
  category: "crm",
  supportedActions: ["create_hubspot_contact", "update_hubspot_deal", "log_hubspot_activity"],
  supportedTriggers: ["contact_created", "deal_updated"],
  oauth: "oauth2",
  authEnvPrefix: "HUBSPOT",
  defaultScopes: ["crm.objects.contacts.read", "crm.objects.deals.write"],
  authorizeUrl: "https://app.hubspot.com/oauth/authorize",
  tokenUrl: "https://api.hubapi.com/oauth/v1/token",
  apiBaseUrl: "https://api.hubapi.com",
  resourceLabel: "HubSpot CRM objects",
};

export const SALESFORCE_CONNECTOR_CONFIG: ConnectorModuleConfig = {
  id: "salesforce",
  name: "Salesforce",
  description: "Contacts, accounts, opportunities, and activities.",
  category: "crm",
  supportedActions: ["create_salesforce_contact", "update_salesforce_opportunity", "log_salesforce_activity"],
  supportedTriggers: ["lead_created", "opportunity_updated"],
  oauth: "oauth2",
  authEnvPrefix: "SALESFORCE",
  defaultScopes: ["api", "refresh_token"],
  authorizeUrl: "https://login.salesforce.com/services/oauth2/authorize",
  tokenUrl: "https://login.salesforce.com/services/oauth2/token",
  apiBaseUrl: "https://login.salesforce.com/services/data/v59.0",
  resourceLabel: "Salesforce records",
};

export const ZENDESK_CONNECTOR_CONFIG: ConnectorModuleConfig = {
  id: "zendesk",
  name: "Zendesk",
  description: "Tickets, comments, status, and priority.",
  category: "helpdesk",
  supportedActions: ["create_zendesk_ticket", "update_zendesk_ticket", "add_zendesk_comment"],
  supportedTriggers: ["ticket_created", "ticket_updated"],
  oauth: "oauth2",
  authEnvPrefix: "ZENDESK",
  defaultScopes: ["read", "write"],
  authorizeUrl: "https://zendesk.com/oauth/authorizations/new",
  tokenUrl: "https://zendesk.com/oauth/tokens",
  apiBaseUrl: "https://zendesk.com/api/v2",
  resourceLabel: "Zendesk tickets",
};

export const CLICKUP_CONNECTOR_CONFIG: ConnectorModuleConfig = {
  id: "clickup",
  name: "ClickUp",
  description: "Tasks, status, comments, and assignees.",
  category: "productivity",
  supportedActions: ["create_clickup_task", "update_clickup_task", "comment_clickup_task"],
  supportedTriggers: ["task_created", "task_status_changed"],
  oauth: "oauth2",
  authEnvPrefix: "CLICKUP",
  defaultScopes: [],
  authorizeUrl: "https://app.clickup.com/api",
  tokenUrl: "https://api.clickup.com/api/v2/oauth/token",
  apiBaseUrl: "https://api.clickup.com/api/v2",
  resourceLabel: "ClickUp tasks",
};

export const ALL_CONNECTOR_CONFIGS: ConnectorModuleConfig[] = [
  GOOGLE_CONNECTOR_CONFIG,
  MICROSOFT_CONNECTOR_CONFIG,
  JIRA_CONNECTOR_CONFIG,
  GITHUB_CONNECTOR_CONFIG,
  GITLAB_CONNECTOR_CONFIG,
  NOTION_CONNECTOR_CONFIG,
  SLACK_CONNECTOR_CONFIG,
  TEAMS_CONNECTOR_CONFIG,
  LINEAR_CONNECTOR_CONFIG,
  HUBSPOT_CONNECTOR_CONFIG,
  SALESFORCE_CONNECTOR_CONFIG,
  ZENDESK_CONNECTOR_CONFIG,
  CLICKUP_CONNECTOR_CONFIG,
];
