/**
 * Art. 28 GDPR Data Processing Agreement (AVV) — versioned customer-facing text.
 *
 * Status for external counsel: READY_FOR_EXTERNAL_LEGAL_REVIEW (internal only —
 * never render that marker on the public page).
 *
 * Not a compliance certification. Does not invent ISO/SOC attestations.
 * Enterprise countersignature remains available via legal@.
 */

import { COMPANY_INFORMATION } from "@/lib/company/company-information";
import { COMPANY_CONTACT } from "@/lib/company/company-contact";
import {
  formatSubprocessorInventoryPlainText,
  SUBPROCESSORS_DOCUMENT_VERSION,
  SUBPROCESSORS_EFFECTIVE_DATE,
  subprocessorsChangeContactLine,
} from "@/lib/company/subprocessors-inventory";

/** Stable document version recorded in organization_contract_acceptances.kind = dpa. */
export const DPA_DOCUMENT_VERSION = "dpa-2026-08-29-v1" as const;

/** INTERNAL ONLY — do not render on customer UI. */
export const DPA_EXTERNAL_REVIEW_STATUS = "READY_FOR_EXTERNAL_LEGAL_REVIEW" as const;

const { productName, legalName, owner, street, postalCode, city, country, vatId } =
  COMPANY_INFORMATION;

export type DpaSection = { heading: string; body: string };

/**
 * Full Art. 28 DPA body + annexes for /data-processing-agreement.
 * Same version string must be used for acceptance evidence.
 */
export function buildDpaPageSections(): DpaSection[] {
  const processorIdentity = [
    `Processor (Auftragsverarbeiter): ${legalName}`,
    `Owner: ${owner}`,
    `Address: ${street}, ${postalCode} ${city}, ${country}`,
    `VAT ID: ${vatId}`,
    `Contact: ${COMPANY_CONTACT.legalEmail}`,
  ].join("\n");

  return [
    {
      heading: "1. Document control",
      body: `Document title: Data Processing Agreement (Art. 28 GDPR / AVV)\nDocument version: ${DPA_DOCUMENT_VERSION}\nProduct: ${productName}\nThis Agreement forms part of the Terms of Service for business customers. It is offered as standard processing terms for self-serve and enterprise procurement review. Individually negotiated addenda may be executed via ${COMPANY_CONTACT.legalEmail} or ${COMPANY_CONTACT.salesEmail} where required.`,
    },
    {
      heading: "2. Parties",
      body: `${processorIdentity}\n\nController (Verantwortlicher): the organization that enters into a ${productName} subscription and determines the purposes and means of processing customer-uploaded personal data in the workspace.\n\nWhere Auroranexis processes personal data as independent controller (for example account administration, billing, security, or its own marketing where consent applies), that processing is described in the Privacy Policy and is outside the processor mandate of this DPA.`,
    },
    {
      heading: "3. Subject matter and duration",
      body: `Subject matter: hosting and operation of the ${productName} multi-tenant B2B SaaS workspace, including storage, retrieval, display, export, support access where instructed, backups, security monitoring, audit logging, and optional features enabled by the Controller.\n\nDuration: for the term of the subscription and any post-termination retention period required by the contract or applicable law, after which personal data under this DPA is deleted or returned as set out below.`,
    },
    {
      heading: "4. Nature and purpose of processing",
      body: `Nature: collection, storage, organization, structuring, retrieval, consultation, use, disclosure by transmission where instructed, restriction, erasure, and destruction — solely as needed to provide the Service.\n\nPurpose: to provide the ${productName} platform to the Controller on documented instructions, including customer support, billing linkage to the Controller’s organization, security and abuse prevention for the Service, and optional AI-assisted features when explicitly enabled by the Controller.`,
    },
    {
      heading: "5. Types of personal data",
      body: `Depending on Controller configuration and use, personal data may include: identification and contact data; authentication credentials and access logs; client and operational records uploaded by the Controller; portal user data; communication content related to support; and metadata generated by use of the Service. The Controller determines which categories are uploaded.`,
    },
    {
      heading: "6. Categories of data subjects",
      body: `Data subjects may include Controller staff and contractors, Controller clients and their personnel, authorized portal users, and other individuals whose data the Controller chooses to process in the workspace.`,
    },
    {
      heading: "7. Documented instructions",
      body: `The Processor processes personal data only on documented instructions from the Controller, including this DPA, the Terms of Service, in-product configuration, and written instructions via support or legal channels — unless Union or Member State law requires otherwise. If an instruction appears to infringe GDPR or other data-protection law, the Processor will inform the Controller without undue delay.`,
    },
    {
      heading: "8. Controller obligations",
      body: `The Controller warrants that it has a valid legal basis for processing and for instructing the Processor; that notices to data subjects are provided where required; and that instructions are lawful. The Controller remains responsible for the accuracy of data uploaded to the Service and for configuring access within its organization.`,
    },
    {
      heading: "9. Processor obligations",
      body: `The Processor shall:\n(a) process personal data only as instructed under this DPA and applicable law;\n(b) ensure persons authorized to process personal data are bound by confidentiality;\n(c) implement appropriate technical and organisational measures (Annex II and Security Policy);\n(d) engage subprocessors only as authorized under Section 12 and Annex III;\n(e) assist the Controller with data-subject requests, taking into account the nature of processing;\n(f) assist with security, breach notification, DPIA, and prior consultation duties where applicable and reasonable given the Service;\n(g) delete or return personal data after end of processing as set out in Section 16;\n(h) make available information necessary to demonstrate compliance and allow audits as set out in Section 15.`,
    },
    {
      heading: "10. Confidentiality",
      body: `The Processor ensures that persons authorized to process personal data have committed themselves to confidentiality or are under an appropriate statutory obligation of confidentiality. Confidentiality obligations survive termination of this DPA for so long as the information remains confidential.`,
    },
    {
      heading: "11. Technical and organisational measures (TOMs)",
      body: `The Processor implements TOMs appropriate to the risk, as summarized in Annex II and described in the public Security Policy. Measures are improved over time; material degradations that reduce the overall security level of processing will not be introduced without assessing impact on this DPA.`,
    },
    {
      heading: "12. Subprocessors",
      body: `The Controller provides general authorization for the Processor to engage subprocessors listed in Annex III (aligned with the public Sub-processors page, inventory version ${SUBPROCESSORS_DOCUMENT_VERSION}, effective ${SUBPROCESSORS_EFFECTIVE_DATE}).\n\nThe Processor remains responsible for subprocessor performance under Art. 28(4) GDPR.\n\nMaterial changes: the Processor will give reasonable advance notice of intended additions or replacements of subprocessors (via workspace administrator communication and/or update of the public list). The Controller may object on reasonable data-protection grounds within the notice period; if no commercially reasonable resolution is reached, the Controller may terminate the affected Service as provided in the Terms. Operational change steps are documented for operators in the repository subprocessor change procedure.`,
    },
    {
      heading: "13. International transfers",
      body: `Where personal data is transferred outside the EEA/UK in connection with the Service, the Processor uses appropriate safeguards such as Standard Contractual Clauses (SCCs) and supplementary measures where required. Transfer details for specific subprocessors are summarized in Annex IV and available on request at ${COMPANY_CONTACT.legalEmail}.`,
    },
    {
      heading: "14. Assistance — data subjects, security, DPIA",
      body: `Taking into account the nature of processing, the Processor assists the Controller by appropriate technical and organisational measures, insofar as possible, for the fulfilment of the Controller’s obligation to respond to requests for exercising data-subject rights.\n\nThe Processor assists with obligations under Arts. 32–36 GDPR (security, breach notification, DPIA, prior consultation) as reasonable for a multi-tenant SaaS provider, including relevant information from security monitoring and incident processes.`,
    },
    {
      heading: "15. Audits and evidence",
      body: `The Processor makes available information necessary to demonstrate compliance with Art. 28 GDPR and this DPA. Audits by the Controller or an mandated auditor are allowed upon reasonable written notice, during business hours, subject to confidentiality, security, and multi-tenant isolation constraints. Where available, the Processor may satisfy audit rights by providing third-party summaries or questionnaires covering the same scope.`,
    },
    {
      heading: "16. Deletion and return",
      body: `After the end of provision of processing services, the Processor shall, at the choice of the Controller, delete or return all personal data processed under this DPA and delete existing copies, unless Union or Member State law requires storage. Workspace export/self-service tools may be used where available; otherwise contact ${COMPANY_CONTACT.supportEmail}. Billing and accounting records retained under legal obligation are outside deletion of processor-held customer content where retention is mandatory.`,
    },
    {
      heading: "17. Personal data breaches",
      body: `The Processor notifies the Controller without undue delay after becoming aware of a personal data breach affecting personal data processed under this DPA, and provides information reasonably available to assist the Controller with its own notification duties.`,
    },
    {
      heading: "18. Liability and hierarchy",
      body: `Liability and limitations are governed by the Terms of Service unless a signed enterprise addendum states otherwise. In case of conflict on data-protection processing terms for Controller-uploaded workspace data, this DPA prevails over general Terms wording on the same subject for that processing.`,
    },
    {
      heading: "19. Governing law",
      body: `Governing law and venue follow the Terms of Service applicable to the subscription, unless a signed addendum provides otherwise.`,
    },
    {
      heading: "20. Contact",
      body: `Data-protection and DPA: ${COMPANY_CONTACT.legalEmail}\nSupport: ${COMPANY_CONTACT.supportEmail}\nSecurity: ${COMPANY_CONTACT.securityEmail}`,
    },
    {
      heading: "ANNEX I — Processing description",
      body: `Service: ${productName} B2B SaaS platform for client operations, reporting, risk/incident tracking, automation, integrations, monitoring, and related workspace features.\n\nProcessing operations: storage and hosting of Controller content; user authentication and authorization within the tenant; application logging and security monitoring; backups; support access when requested; optional AI features when enabled.\n\nRetention: for the subscription term plus any contractual or statutory retention applicable to specific record types (accounting records may be retained longer under law).`,
    },
    {
      heading: "ANNEX II — Technical and organisational measures (TOMs)",
      body: `Measures currently described for the Service include:\n• Encryption in transit (TLS) for application access\n• Logical tenant isolation and role-based access controls within the application\n• Authentication requirements for administrative and user access\n• Access limited to authorized personnel on a need-to-know basis\n• Audit logging of relevant security and administrative events\n• Monitoring and incident-response procedures, including customer breach notification where required\n• Vulnerability intake via ${COMPANY_CONTACT.securityEmail} / published vulnerability disclosure policy\n• Backups and recovery processes appropriate to the hosting architecture\n\nThe public Security Policy provides additional operational detail. Auroranexis does not claim formal ISO/SOC certification on this page unless a current attestation is separately published.`,
    },
    {
      heading: "ANNEX III — Approved subprocessors",
      body: `Inventory version: ${SUBPROCESSORS_DOCUMENT_VERSION}\nEffective date: ${SUBPROCESSORS_EFFECTIVE_DATE}\n\n${formatSubprocessorInventoryPlainText()}\n\n${subprocessorsChangeContactLine()}\nThe live public list is also published at /subprocessors.`,
    },
    {
      heading: "ANNEX IV — International transfers",
      body: `Transfers outside the EEA may occur depending on subprocessor configuration (for example certain analytics, error monitoring, or optional AI providers).\n\nSafeguards: Standard Contractual Clauses and supplementary measures where required.\n\nSpecific SCC modules, transfer impact assessments, and current subprocessor DPA links are available to Controllers on request at ${COMPANY_CONTACT.legalEmail}. This Annex does not invent data-centre locations beyond what is stated in Annex III.`,
    },
  ];
}
