import type { DocPageInput } from "@/lib/docs/types";

export const BILLING_DOC: DocPageInput = {
  slug: "billing",
  title: "Billing",
  description:
    "Plans, Stripe checkout, invoices, payment methods, and subscription management.",
  intro:
    "Billing is managed in Settings → Billing. Workspace owners and admins with billing permissions can compare plans, start Stripe checkout, download invoices, update payment methods, and open the Stripe customer portal to manage subscriptions.",
  callouts: [
    {
      variant: "info",
      title: "Who can manage billing",
      body: "Only workspace owners and admins with billing permissions can change plans, apply discount codes, or open the customer portal. Staff and viewer roles cannot modify payment details or subscription settings.",
    },
  ],
  sections: [
    {
      title: "Overview",
      paragraphs: [
        "Auroranexis subscriptions are billed through Stripe, a PCI-compliant payment processor. Your workspace plan determines feature access, usage limits, seat counts, and support tier. All billing activity — plan selection, checkout, invoices, and subscription changes — is accessible from Settings → Billing within the application.",
        "Billing is tied to your organization, not individual user accounts. When you upgrade or downgrade, the change applies to the entire workspace. Usage meters and effective limits are reflected in Settings → Usage and update after plan changes are processed.",
        "Three self-serve tiers are available: Professional for growing teams that need automation and client portal delivery, Business for agencies requiring advanced compliance features and white-label branding, and Enterprise for organizations that need custom limits and negotiated arrangements. Enterprise requests are submitted from Settings → Billing or Settings → Enterprise and reviewed separately from standard checkout.",
      ],
    },
    {
      title: "Purpose",
      paragraphs: [
        "The billing module gives agency operators a self-serve way to subscribe, pay, and manage their Auroranexis workspace without manual invoicing or back-and-forth with sales for standard plans. Stripe handles payment collection, card storage, and invoice generation; Auroranexis surfaces plan status, usage against limits, and links to the customer portal.",
        "For agencies on Professional or Business tiers, billing is fully automated. You choose a plan, complete checkout, and manage renewals through the customer portal. Enterprise customers may have custom arrangements negotiated separately, but day-to-day invoice access and payment method management still flow through the same billing interface where applicable.",
        "The billing page also serves as the starting point for understanding what your plan includes. Before upgrading, compare tier summaries against your current consumption in Settings → Usage so you select a plan that covers client count, seats, API volume, and feature requirements without unnecessary overspend.",
      ],
    },
    {
      title: "Core Concepts",
      bullets: [
        "Workspace plan — the subscription tier (Professional, Business, or Enterprise) that governs features and limits.",
        "Billing cycle — monthly or annual period during which your subscription is active and renewed.",
        "Proration — a partial charge or credit applied when you change plans mid-cycle.",
        "Customer portal — Stripe's hosted page for payment methods, invoices, and subscription management.",
        "Usage limits — caps on clients, seats, API calls, monitoring targets, and other resources defined by your plan.",
        "Past due — a subscription status indicating a failed or overdue payment that requires attention.",
        "Invoice — a billing document generated by Stripe for each charge, available as PDF from Settings → Billing or the customer portal.",
      ],
      paragraphs: [
        "Plan changes and payment events are reflected in Settings → Billing after Stripe confirms the transaction. There may be a short delay between completing checkout and seeing the updated plan in the dashboard. Payment card details never appear in Auroranexis — they are entered and stored entirely within Stripe's secure checkout and customer portal flows.",
      ],
    },
    {
      title: "Features",
      bullets: [
        "Plan comparison — view Professional, Business, and Enterprise tiers with feature and limit summaries.",
        "Stripe checkout — secure, hosted payment flow for new subscriptions and upgrades.",
        "Invoice history — access recent invoices with payment status and PDF downloads where available.",
        "Customer portal — update payment methods, view billing history, and manage subscription details.",
        "Discount codes — apply promotional codes during checkout when eligible.",
        "Usage visibility — cross-reference your plan limits with current consumption in Settings → Usage.",
        "Enterprise requests — submit custom plan inquiries from Settings → Billing or Settings → Enterprise.",
      ],
      subsections: [
        {
          title: "Plan tiers",
          bullets: [
            "Professional — for growing agencies with core client operations, automation, client portal delivery, and essential monitoring.",
            "Professional — adds automation workflows, client portal delivery, integrations, and higher usage limits for growing teams.",
            "Business — includes advanced compliance features, white-label branding, expanded limits, and priority support options.",
            "Enterprise — custom limits, tailored onboarding, plan overrides, and dedicated support; request via Settings → Billing or Enterprise.",
          ],
        },
        {
          title: "Payment methods and invoices",
          paragraphs: [
            "Payment methods are managed exclusively through the Stripe customer portal. You can add credit or debit cards, set a default method, and remove expired cards without exposing card numbers in the Auroranexis dashboard. Invoices for each billing period appear in Settings → Billing with payment status, and full history including PDF downloads is available in the customer portal.",
          ],
        },
      ],
    },
    {
      title: "Step-by-step usage",
      subsections: [
        {
          title: "Subscribe or upgrade via Stripe checkout",
          ordered: [
            "Sign in as an owner or admin and open Settings → Billing.",
            "Review the plan comparison table and select the tier that matches your agency's needs.",
            "Click the upgrade or subscribe action to start Stripe checkout.",
            "Enter payment details on the secure Stripe checkout page.",
            "Apply a discount code during checkout if you have one.",
            "Complete payment and return to Auroranexis.",
            "Verify your new plan and limits appear in Settings → Billing and Settings → Usage.",
          ],
        },
        {
          title: "Download invoices",
          ordered: [
            "Open Settings → Billing.",
            "Scroll to the invoice history section.",
            "Locate the invoice by date or amount.",
            "Download the PDF or view payment status as shown.",
            "For older invoices, open the Stripe customer portal for the full billing history.",
          ],
        },
        {
          title: "Update payment methods",
          ordered: [
            "Open Settings → Billing.",
            "Select Open customer portal (or the equivalent billing action).",
            "In the Stripe customer portal, add a new card or replace an existing payment method.",
            "Set the new method as default if prompted.",
            "Return to Auroranexis and confirm billing status shows as active.",
          ],
        },
        {
          title: "Change or cancel a subscription",
          ordered: [
            "Open Settings → Billing and launch the Stripe customer portal.",
            "To upgrade or downgrade, select the desired plan change and confirm.",
            "Review proration details shown in the portal before confirming mid-cycle changes.",
            "To cancel, choose cancel subscription and follow the portal prompts.",
            "Export any critical data before access ends if cancelling.",
            "Enterprise customers should coordinate changes with their account contact.",
          ],
        },
      ],
    },
    {
      title: "Best Practices",
      bullets: [
        "Keep a valid payment method on file and update cards before they expire to avoid service interruption.",
        "Ensure your billing email address receives Stripe invoice and failure notifications.",
        "Review Settings → Usage after any plan change to confirm new limits meet operational needs.",
        "Export reports and client data before cancelling if you may need records after access ends.",
        "Apply discount codes during checkout — they cannot typically be applied retroactively to existing subscriptions.",
        "Restrict billing permissions to owners and trusted admins who manage financial decisions.",
        "For annual billing, note renewal dates and budget accordingly; annual plans may offer cost savings over monthly billing.",
        "Compare plan tiers against projected growth — upgrading before hitting hard limits avoids blocked operations.",
      ],
    },
    {
      title: "Examples",
      subsections: [
        {
          title: "Marketing agency",
          paragraphs: [
            "A multi-brand marketing agency on Business approaches client and seat limits while rolling out white-label portal access for quarterly campaign reports. The owner opens Settings → Billing, reviews tier summaries against projected growth, and completes checkout to Business if not already subscribed. Invoice PDFs download for finance, and Settings → Usage confirms headroom before enabling scheduled report delivery to forty new portal users across two sub-brands.",
          ],
        },
        {
          title: "AI automation agency",
          paragraphs: [
            "A twelve-person automation shop on Professional approaches monthly automation run limits while onboarding webhook-driven workflows for thirty clients. The founder opens Settings → Billing, compares Business tier automation allowances, and completes Stripe checkout. Prorated charges apply for the remainder of the cycle. After upgrade, the team confirms expanded run limits in Settings → Usage before enabling high-volume incident-creation automations.",
          ],
        },
        {
          title: "MSP",
          paragraphs: [
            "A twelve-person MSP on Professional needs expanded client and portal capacity for forty managed clients. The operations director opens Settings → Billing, selects Business, and completes Stripe checkout. The upgrade takes effect immediately with prorated charges for the remainder of the billing cycle. The team verifies automation and portal modules remain available and checks Settings → Usage for updated client and seat limits before rolling out portal access to key accounts.",
          ],
        },
        {
          title: "Consultancy",
          paragraphs: [
            "A three-person consultancy winding down client operations opens Settings → Billing and launches the customer portal to cancel at period end. Before the final billing date, they export client reports, incident histories, and risk registers from each module. The subscription remains active until the paid period ends, giving the team time to archive records for their internal compliance requirements.",
          ],
        },
        {
          title: "Enterprise deployment",
          paragraphs: [
            "An agency operating four sub-brands manages one hundred eighty clients and exceeds Business plan limits. The owner submits an enterprise request from Settings → Billing with required client count, seat needs, and white-label requirements. After review and approval, custom limits appear in Settings → Enterprise and billing may transition to a negotiated arrangement while invoice access remains available through the billing page.",
          ],
        },
      ],
    },
    {
      title: "Troubleshooting",
      table: {
        caption: "Common billing issues",
        headers: ["Problem", "Cause", "Solution"],
        rows: [
          [
            "Checkout completed but plan did not update",
            "Stripe confirmation may still be processing",
            "Refresh Settings → Billing and wait a few minutes. If unchanged, contact support with the approximate checkout time.",
          ],
          [
            "Discount code rejected at checkout",
            "Code expired, ineligible for selected tier, or already redeemed",
            "Verify the code is active and applicable to your chosen plan. Contact the code issuer if issues persist.",
          ],
          [
            "Workspace shows past due or limited access",
            "Payment failed due to expired card, insufficient funds, or bank decline",
            "Open the Stripe customer portal from Settings → Billing and update your default payment method immediately.",
          ],
          [
            "Cannot open the customer portal",
            "Your role lacks billing permissions",
            "Ask a workspace owner or admin with billing access to update payment methods or make subscription changes.",
          ],
          [
            "Invoice PDF not available in billing history",
            "Invoice generation may still be in progress",
            "Check the customer portal for the full invoice history; PDFs typically appear within minutes of payment.",
          ],
          [
            "Downgrade not reflected in feature access",
            "Downgrades may apply at the next billing period",
            "Check the customer portal for the effective date. Export data if features will be removed at period end.",
          ],
          [
            "Unexpected charge amount after plan change",
            "Mid-cycle proration for upgrades or partial credits for downgrades",
            "Review invoice line items in the customer portal; proration explains partial-period charges.",
          ],
        ],
      },
    },
  ],
  faq: [
    {
      question: "Who can manage billing in my workspace?",
      answer:
        "Workspace owners and admins with billing permissions can change plans, apply discount codes, and open the Stripe customer portal. Other roles cannot modify subscription or payment settings.",
    },
    {
      question: "Where are my payment details stored?",
      answer:
        "Payment card and bank details are collected and stored by Stripe, not in Auroranexis application databases. The billing page shows subscription status without exposing sensitive payment data.",
    },
    {
      question: "What happens when I cancel my subscription?",
      answer:
        "After cancellation, your workspace remains accessible until the end of the current paid billing period unless otherwise stated in your agreement. Export critical data before access ends.",
    },
    {
      question: "Can I switch between monthly and annual billing?",
      answer:
        "Billing interval options depend on the plan and checkout configuration available at the time of subscription. Use the customer portal or contact support for interval change requests.",
    },
    {
      question: "How do I get a copy of an invoice for accounting?",
      answer:
        "Open Settings → Billing to view recent invoices and download PDFs. The Stripe customer portal provides the full invoice history.",
    },
    {
      question: "What is the difference between Business and Enterprise?",
      answer:
        "Business is a self-serve tier with expanded limits and features available through Stripe checkout. Enterprise involves a reviewed request process with custom limits, onboarding, and negotiated terms submitted from Settings → Enterprise or Settings → Billing.",
    },
  ],
  relatedLinks: [
    { href: "/docs/enterprise", label: "Enterprise" },
    { href: "/docs/security", label: "Security" },
    { href: "/docs/getting-started", label: "Getting started" },
  ],
};

export const SECURITY_DOC: DocPageInput = {
  slug: "security",
  title: "Security",
  description:
    "Organization-scoped access, role-based permissions, encryption, audit trails, and secure billing.",
  intro:
    "Auroranexis is designed for agency operations with organization-scoped data, role-based access control, encrypted transport and storage, and secure billing through Stripe. This page describes security controls available to customers — not internal platform infrastructure.",
  callouts: [
    {
      variant: "warning",
      title: "Compliance readiness, not certification claims",
      body: "Auroranexis describes security practices and compliance readiness where applicable to your plan. We do not claim SOC 2, ISO 27001, HIPAA, or other third-party certifications unless explicitly published for your deployment. Refer to your agreement and the Compliance documentation for plan-specific capabilities.",
    },
  ],
  sections: [
    {
      title: "Overview",
      paragraphs: [
        "Security in Auroranexis is a shared responsibility between the platform and your agency. The platform provides organization isolation, role-based access, encryption, activity logging, and secure payment handling. Your agency controls who has access, which roles they hold, how API keys are managed, and how client portal users are provisioned.",
        "Every workspace operates within a strict organizational boundary. Users, API keys, integrations, and portal accounts are scoped to a single organization. Cross-organization data access is not available through normal application or API operations.",
        "This documentation covers customer-facing security controls: how data is scoped, who can access what, how credentials are handled, and how to report concerns. It does not describe internal platform administration, infrastructure topology, or vendor-specific operational details.",
      ],
    },
    {
      title: "Purpose",
      paragraphs: [
        "Agencies manage sensitive client data — reports, incidents, risk assessments, and operational metrics. The security model ensures that internal team members see only what their role permits, client portal users access only their assigned client, and billing data never resides in application databases.",
        "Audit trails and activity history support internal review and compliance workflows where enabled on your plan. Security controls are designed to be understandable and actionable by agency administrators without requiring specialized security tooling.",
        "For security concerns, vulnerabilities, or suspected unauthorized access, contact security@auroranexis.com. Include reproduction steps and impact assessment without sharing live credentials or unnecessary client data in your initial report.",
      ],
    },
    {
      title: "Core Concepts",
      bullets: [
        "Organization scope — all data, users, and API keys belong to a single workspace; there is no cross-tenant access.",
        "Role-based access control (RBAC) — permissions are assigned through predefined roles with optional granular adjustments.",
        "Least privilege — users receive the minimum access needed for their responsibilities.",
        "Encryption in transit — all web and API traffic uses TLS.",
        "Encryption at rest — platform data stores encrypt stored data.",
        "Audit trail — a chronological record of significant actions performed in the workspace.",
        "Secure billing — payment details are handled entirely by Stripe; Auroranexis never stores card numbers.",
        "Compliance readiness — plan-specific capabilities that support your internal compliance program without implying third-party certification.",
      ],
    },
    {
      title: "Features",
      subsections: [
        {
          title: "Organization-scoped access",
          bullets: [
            "Each workspace is fully isolated — users only see data belonging to their organization.",
            "Client portal users are scoped to a single client and cannot access internal settings, other clients, or team management.",
            "API keys are tied to the organization that created them and carry explicit scopes.",
            "Integrations and automation credentials are organization-specific and not shared across workspaces.",
          ],
        },
        {
          title: "Role-based access control",
          bullets: [
            "Owner — full workspace control including billing, team management, and all operational modules.",
            "Admin — manage operations, settings, and most modules; billing access depends on assigned permissions.",
            "Staff — day-to-day operational access for assigned clients, reports, incidents, and workflows.",
            "Viewer — read-focused access suitable for reporting, review, and oversight roles.",
          ],
          paragraphs: [
            "Manage roles and team membership in Settings → Team. Review permissions when onboarding new staff and promptly adjust or revoke access during offboarding.",
          ],
        },
        {
          title: "Data protection",
          bullets: [
            "TLS encryption for all web dashboard and API communication.",
            "Encryption at rest for platform data stores.",
            "Industry-standard authentication flows for password handling.",
            "Session cookies protect dashboard access; sign out on shared or public devices.",
            "API keys are displayed only once at creation and stored as secure hashes.",
          ],
        },
        {
          title: "Audit trails",
          bullets: [
            "Activity history records significant workspace actions with timestamps and actor information.",
            "Compliance and audit views (where enabled on your plan) support structured review workflows.",
            "Export or archive records according to your internal retention policy.",
          ],
        },
        {
          title: "Secure billing",
          bullets: [
            "Payment card and bank details are collected and stored by Stripe — not in Auroranexis databases.",
            "Billing pages display subscription status without exposing card numbers or CVV data.",
            "Only authorized roles can initiate checkout or open the Stripe customer portal.",
          ],
        },
      ],
    },
    {
      title: "Step-by-step usage",
      subsections: [
        {
          title: "Configure team roles",
          ordered: [
            "Open Settings → Team.",
            "Invite new members with the appropriate role (Owner, Admin, Staff, or Viewer).",
            "Review existing members and downgrade permissions where access exceeds job requirements.",
            "Remove or deactivate accounts promptly when staff leave the agency.",
          ],
        },
        {
          title: "Manage API key security",
          ordered: [
            "Open Settings → API.",
            "Create keys with only the scopes required for each integration.",
            "Store keys in a secrets manager — never commit them to source control.",
            "Revoke keys immediately when integrations are decommissioned or team members with access leave.",
          ],
        },
        {
          title: "Provision client portal users safely",
          ordered: [
            "From the client detail page, open portal user management.",
            "Invite only required client contacts with portal-appropriate access.",
            "Review portal user lists periodically and remove inactive accounts.",
            "Confirm white-label branding does not expose internal agency information unintentionally.",
          ],
        },
        {
          title: "Review activity and audit records",
          ordered: [
            "Open the Activity module or compliance audit views (if enabled on your plan).",
            "Filter by date range, user, or action type as needed.",
            "Investigate unexpected entries and document findings per your internal policy.",
            "Export records for retention if required by your compliance program.",
          ],
        },
        {
          title: "Report a security issue",
          ordered: [
            "Email security@auroranexis.com with a description of the concern.",
            "Include steps to reproduce, affected modules, and potential impact.",
            "Avoid sharing live credentials or client data in the initial report.",
            "Allow reasonable time for triage and response before public disclosure.",
          ],
        },
      ],
    },
    {
      title: "Best Practices",
      bullets: [
        "Enforce strong, unique passwords for all team accounts.",
        "Follow least-privilege when assigning roles — grant write access only where needed.",
        "Offboard team members the same day they depart; revoke API keys and integration credentials they managed.",
        "Review team membership and portal user lists at least quarterly.",
        "Limit client portal users to the minimum contacts required for each engagement.",
        "Never share API keys via email, chat, or unencrypted documents.",
        "Monitor activity history for unexpected configuration or data access patterns.",
        "Keep billing permissions restricted to owners and designated financial administrators.",
        "Document your internal access review process and align it with client contractual obligations.",
      ],
    },
    {
      title: "Examples",
      subsections: [
        {
          title: "Marketing agency",
          paragraphs: [
            "A marketing agency operating three sub-brands provisions portal users per client with white-label branding. Each portal account is scoped to a single client. The admin reviews portal user lists quarterly, removes contacts who changed roles at client organizations, and verifies no internal agency email addresses appear in client-facing portal configurations.",
          ],
        },
        {
          title: "AI automation agency",
          paragraphs: [
            "An automation agency rotates integration credentials after a contractor offboards. The admin revokes the contractor's Staff account in Settings → Team, deletes their personal API keys in Settings → API, and updates shared secrets in Automation → Integrations → Secrets. Activity history for the final two weeks is exported before the next automation run batch executes against production clients.",
          ],
        },
        {
          title: "MSP",
          paragraphs: [
            "An MSP with twenty-five clients hires two junior analysts who need incident visibility but not billing or API access. The admin invites them as Staff in Settings → Team, assigns them to relevant client groups, and confirms they cannot access Settings → Billing or Settings → API. Portal users for each client are limited to the client's IT director and one backup contact.",
          ],
        },
        {
          title: "Consultancy",
          paragraphs: [
            "A small IT consultancy's client requests evidence of access controls. The owner exports activity history for the relevant date range, documents the RBAC matrix showing Owner, Admin, Staff, and Viewer assignments, and confirms billing data is handled by Stripe without card storage in Auroranexis. The package supports the client's vendor review without claiming third-party certification on the agency's behalf.",
          ],
        },
        {
          title: "Enterprise deployment",
          paragraphs: [
            "A multi-region MSSP admin notices SLA configuration changed without explanation during an enterprise rollout. They open Activity, filter by the settings module and the relevant date range, and identify the user and timestamp of the change. After confirming whether the change was authorized, they restore the previous configuration, document the incident per internal policy, and align regional Admin roles before expanding portal access.",
          ],
        },
      ],
    },
    {
      title: "Troubleshooting",
      table: {
        caption: "Common security issues",
        headers: ["Problem", "Cause", "Solution"],
        rows: [
          [
            "User cannot access a module",
            "Role or plan tier lacks the required feature permission",
            "Verify the user's role in Settings → Team and confirm the workspace plan includes the module.",
          ],
          [
            "Portal user sees wrong client data",
            "Portal account assigned to incorrect client",
            "Confirm the portal account is linked to the correct client only; remove and re-invite if misassigned.",
          ],
          [
            "API key returns 401 Unauthorized",
            "Key revoked, expired, or missing required scopes",
            "Create a new key with appropriate scopes in Settings → API; revoke the old key.",
          ],
          [
            "Expected action not in activity history",
            "Not all read operations are logged",
            "Significant write and configuration actions are captured; verify filters and date range in Activity.",
          ],
          [
            "Staff member can access billing settings",
            "Billing permissions granted beyond role defaults",
            "Review role assignments in Settings → Team and remove billing access from non-owner accounts.",
          ],
          [
            "Suspected unauthorized access",
            "Compromised credentials or misconfigured integration",
            "Revoke affected API keys, review activity history, reset passwords, and email security@auroranexis.com.",
          ],
          [
            "Client asks about SOC 2 or ISO certification",
            "Misunderstanding of platform compliance posture",
            "Refer to your agreement and Compliance documentation; Auroranexis describes readiness, not certification claims.",
          ],
        ],
      },
    },
  ],
  faq: [
    {
      question: "Is Auroranexis SOC 2 or ISO 27001 certified?",
      answer:
        "Auroranexis does not claim third-party certifications unless explicitly published for your deployment. We describe security practices and compliance readiness where applicable. Refer to your agreement and the Compliance documentation for plan-specific capabilities.",
    },
    {
      question: "Where is payment information stored?",
      answer:
        "Payment card and bank details are stored by Stripe, a PCI-compliant payment processor. Auroranexis does not store card numbers or CVV data in application databases.",
    },
    {
      question: "Can staff members access billing settings?",
      answer:
        "Only workspace owners and admins with billing permissions can manage subscriptions and open the Stripe customer portal. Staff and viewer roles cannot modify billing settings.",
    },
    {
      question: "How do I report a security vulnerability?",
      answer:
        "Email security@auroranexis.com with reproduction steps and impact assessment. Do not include live credentials or unnecessary client data in your report.",
    },
    {
      question: "Are API keys retrievable after creation?",
      answer:
        "No. API keys are shown once at creation. If a key is lost, revoke it and create a new one with the same scopes.",
    },
    {
      question: "What does compliance readiness mean?",
      answer:
        "Compliance readiness refers to plan-specific features — such as audit views, activity exports, and data handling practices — that support your internal compliance program. It does not mean Auroranexis holds a specific third-party certification on your behalf.",
    },
  ],
  relatedLinks: [
    { href: "/docs/compliance", label: "Compliance" },
    { href: "/docs/api", label: "API" },
    { href: "/docs/client-portal", label: "Client portal" },
  ],
};

export const API_DOC: DocPageInput = {
  slug: "api",
  title: "API",
  description:
    "API keys, scopes, webhooks, rate limits, and integration guidelines.",
  intro:
    "The Auroranexis REST API lets your workspace integrate with external systems, automate operational workflows, and receive event notifications. Manage keys and webhook endpoints in Settings → API. For endpoint-level details, use the interactive OpenAPI reference at /api/docs.",
  callouts: [
    {
      variant: "tip",
      title: "OpenAPI reference",
      body: "The interactive API reference at /api/docs provides full endpoint documentation, request and response schemas, and try-it-out functionality. Access it after signing in or from Settings → API.",
    },
    {
      variant: "warning",
      title: "Protect your API keys",
      body: "API keys grant access to your organization's data. Store them in a secrets manager, never commit them to source control, and revoke keys immediately when no longer needed. Documentation uses placeholder keys only — never use example values in production.",
    },
  ],
  sections: [
    {
      title: "Overview",
      paragraphs: [
        "The Auroranexis API is a RESTful, organization-scoped interface. Every request is authenticated with an API key that carries explicit scopes limiting what the key can read or write. The API follows standard HTTP conventions — JSON request and response bodies, appropriate status codes, and TLS encryption for all traffic.",
        "API access availability and rate limits depend on your subscription plan. Plan-gated features such as AI execution and predictive analytics require both the appropriate scope and an eligible plan tier.",
        "All key management — creation, scope selection, revocation, and webhook registration — happens in Settings → API. The OpenAPI reference at /api/docs is the authoritative source for endpoint paths, request schemas, and response formats.",
      ],
    },
    {
      title: "Purpose",
      paragraphs: [
        "Agencies use the API to synchronize client data with CRM systems, trigger automations from external events, publish reports programmatically, and build custom internal tools on top of Auroranexis operational data. Webhooks complement the API by pushing event notifications to your endpoints when platform events occur.",
        "The API is designed for server-to-server integration. Keys should be treated as sensitive credentials with the same care as passwords or integration secrets. Never embed keys in client-side JavaScript, mobile applications, or public repositories.",
        "Rate limits protect platform stability for all customers. Monitor usage in Settings → API and Settings → Usage, and implement backoff strategies in your integration code when limits are approached.",
      ],
    },
    {
      title: "Core Concepts",
      bullets: [
        "API key — a bearer token that authenticates requests on behalf of your organization.",
        "Scope — a permission label that limits a key to specific read or write operations.",
        "Base URL — the HTTPS origin for all API requests to your workspace.",
        "Webhook endpoint — a URL registered to receive HTTPS POST event deliveries.",
        "Rate limit — a per-organization cap on request frequency to protect platform stability.",
        "Plan gating — certain endpoints require features enabled on your subscription tier.",
        "Placeholder keys — documentation examples such as ax_live_example_key_abc123 are not valid credentials.",
      ],
    },
    {
      title: "Features",
      bullets: [
        "Organization-scoped REST endpoints for clients, reports, risks, incidents, automation, and more.",
        "Granular scope selection when creating API keys in Settings → API.",
        "Outbound webhook registration for platform event notifications.",
        "Interactive OpenAPI reference at /api/docs with schema definitions.",
        "Usage and rate limit visibility in Settings → API and Settings → Usage.",
        "Personal and workspace-wide key types depending on integration needs.",
      ],
      subsections: [
        {
          title: "Available scopes",
          paragraphs: [
            "Grant only the scopes your integration requires. Each scope pair follows a resource.action pattern. Keys with write scopes can modify data — apply least privilege.",
          ],
          bullets: [
            "clients.read / clients.write — client records and metadata.",
            "reports.read / reports.write — reports, templates, and publishing.",
            "risks.read / risks.write — risk register entries.",
            "incidents.read / incidents.write — incident records and status.",
            "automation.read / automation.write — workflow definitions and executions.",
            "integrations.read / integrations.write — connector configuration.",
            "webhooks.write — register and manage outbound webhook endpoints.",
            "activity.read — workspace activity feed.",
            "billing.read — subscription and usage summaries (read-only).",
            "settings.read — non-sensitive settings visibility.",
            "health.read — health and monitoring summaries.",
            "ai.execute / predictive.read — plan-gated intelligence features.",
          ],
        },
      ],
    },
    {
      title: "Step-by-step usage",
      subsections: [
        {
          title: "Create an API key",
          ordered: [
            "Open Settings → API.",
            "Click Create key and enter a descriptive name identifying the integration.",
            "Select only the scopes required for the integration's operations.",
            "Copy the key immediately when displayed — it cannot be retrieved again.",
            "Store the key in your secrets manager or integration configuration.",
          ],
        },
        {
          title: "Make an API request",
          ordered: [
            "Confirm your key has the required scope for the target endpoint.",
            "Consult /api/docs for the correct path, method, and request body schema.",
            "Send an HTTPS request to the appropriate /api/v1/ path.",
            "Include the Authorization header with your key as a Bearer token.",
            "Handle response status codes and parse the JSON response body.",
          ],
        },
        {
          title: "Register a webhook endpoint",
          ordered: [
            "Open Settings → API and navigate to webhook configuration.",
            "Register your HTTPS endpoint URL.",
            "Select the event types your receiver should handle.",
            "Ensure your endpoint accepts POST requests and responds with a 2xx status.",
            "Monitor delivery status and address failures promptly.",
          ],
        },
        {
          title: "Handle rate limits",
          ordered: [
            "Implement exponential backoff when receiving HTTP 429 responses.",
            "Review current usage in Settings → API and Settings → Usage.",
            "Batch or cache read operations where possible to reduce call volume.",
            "Contact support or submit an enterprise request if sustained higher limits are required.",
          ],
        },
      ],
    },
    {
      title: "Best Practices",
      bullets: [
        "Apply least-privilege scope selection — never grant write scopes unless the integration requires them.",
        "Use workspace keys for shared services; personal keys for individual scripts or development.",
        "Rotate keys periodically and revoke unused keys immediately.",
        "Implement idempotent handlers for webhook receivers to safely process duplicate deliveries.",
        "Log API errors with correlation IDs from response headers when available.",
        "Use the OpenAPI reference at /api/docs as the source of truth for endpoint behavior.",
        "Never expose API keys in client-side JavaScript, mobile apps, or public repositories.",
        "Test integrations against a dedicated key with minimal scopes before granting production access.",
      ],
    },
    {
      title: "Examples",
      subsections: [
        {
          title: "Marketing agency",
          paragraphs: [
            "A marketing agency registers https://integrations.example.com/auroranexis/events as a webhook endpoint with events for report.published and incident.created. When a report is published, Auroranexis sends an HTTPS POST with a JSON payload. The receiver validates the request, processes the event idempotently, and returns HTTP 200. Failed deliveries appear in webhook logs for investigation.",
          ],
        },
        {
          title: "AI automation agency",
          paragraphs: [
            "An automation agency connects a workflow engine to Auroranexis using scoped API keys. The admin creates a key with clients.read and incidents.write scopes so failed automation runs can open incidents automatically. POST requests include client ID, severity, and a description referencing the workflow run ID. Write scopes are limited to incidents — report and billing endpoints remain unreachable from the integration service account.",
          ],
        },
        {
          title: "MSP",
          paragraphs: [
            "An MSP syncs client names and status to ConnectWise nightly. The admin creates a key named CRM Sync in Settings → API with only the clients.read scope. The integration sends GET /api/v1/clients with Authorization: Bearer ax_live_example_key_abc123. The response JSON array is parsed and upserted into the CRM. No write scopes are granted because the sync is one-directional.",
          ],
        },
        {
          title: "Consultancy",
          paragraphs: [
            "A small consultancy builds an internal dashboard showing subscription usage against plan limits. The owner creates a read-only key with billing.read scope in Settings → API. A nightly script fetches usage summaries and displays them alongside client counts from a separate clients.read key. Write scopes are intentionally excluded from both keys.",
          ],
        },
        {
          title: "Enterprise deployment",
          paragraphs: [
            "An MSSP's monitoring stack auto-creates incidents when thresholds are breached across eighty enterprise clients. The admin creates a dedicated key with incidents.write scope and documents rate-limit headroom in Settings → Enterprise before enabling production traffic. POST requests to /api/v1/incidents include title, severity, client ID, and description fields. A 201 response returns the new incident ID for tracking in the external monitoring dashboard.",
          ],
        },
      ],
    },
    {
      title: "Troubleshooting",
      table: {
        caption: "Common API issues",
        headers: ["Problem", "Cause", "Solution"],
        rows: [
          [
            "401 Unauthorized on API request",
            "Key revoked, malformed, or missing from Authorization header",
            "Verify the Bearer token format and confirm the key is active in Settings → API.",
          ],
          [
            "403 Forbidden on API request",
            "Key lacks required scope or plan does not include the feature",
            "Create a new key with the needed scope or upgrade your plan if the feature is plan-gated.",
          ],
          [
            "404 Not Found for resource",
            "Incorrect resource ID or endpoint path",
            "Verify the path and ID against /api/docs; confirm the resource exists in your workspace.",
          ],
          [
            "429 Too Many Requests",
            "Request rate exceeds plan limit",
            "Implement exponential backoff, reduce call frequency, and review usage in Settings → Usage.",
          ],
          [
            "Webhook deliveries failing",
            "Endpoint unreachable or returning non-2xx responses",
            "Confirm the endpoint accepts HTTPS POST and returns 2xx; check webhook logs for error details.",
          ],
          [
            "API key not visible after creation",
            "Keys are shown only once at creation",
            "Revoke the lost key and create a new one with the same scopes.",
          ],
          [
            "Empty results despite data existing",
            "Query parameters filtering results or wrong organization scope",
            "Keys only access your workspace data; review query parameters and pagination in /api/docs.",
          ],
        ],
      },
    },
  ],
  faq: [
    {
      question: "Where do I find endpoint documentation?",
      answer:
        "The interactive OpenAPI reference at /api/docs provides full endpoint details, schemas, and examples. Access it after signing in or from Settings → API.",
    },
    {
      question: "Can I retrieve an API key after creating it?",
      answer:
        "No. Keys are displayed once at creation. If lost, revoke the key and create a new one with the same scopes.",
    },
    {
      question: "What rate limits apply to my workspace?",
      answer:
        "Rate limits vary by plan and protect platform stability. Review usage in Settings → API and Settings → Usage. Contact support or request enterprise limits if your integration requires sustained higher throughput.",
    },
    {
      question: "Do webhooks require a specific scope?",
      answer:
        "Registering webhook endpoints requires the webhooks.write scope on the API key used for registration. Receiving webhook deliveries does not require an API key on your endpoint, but you should validate incoming requests according to your integration design.",
    },
    {
      question: "Are example keys in documentation real?",
      answer:
        "No. Documentation uses placeholder keys such as ax_live_example_key_abc123. Never use example values in production integrations.",
    },
    {
      question: "Can I use the API on the Professional plan?",
      answer:
        "API access and rate limits depend on your subscription tier. Review Settings → API for availability and consult /api/docs for plan-gated endpoints such as ai.execute.",
    },
  ],
  relatedLinks: [
    { href: "/api/docs", label: "OpenAPI reference" },
    { href: "/docs/integrations", label: "Integrations" },
    { href: "/docs/security", label: "Security" },
  ],
};

export const ENTERPRISE_DOC: DocPageInput = {
  slug: "enterprise",
  title: "Enterprise",
  description:
    "Custom plans, onboarding, plan overrides, priority support, and custom limits.",
  intro:
    "Enterprise is for agencies that need custom limits, tailored onboarding, negotiated plan overrides, or priority support beyond standard self-serve tiers. Submit a request from Settings → Enterprise or Settings → Billing — enterprise arrangements are reviewed by the Auroranexis team and are not instant self-serve upgrades.",
  callouts: [
    {
      variant: "info",
      title: "Enterprise is a reviewed process",
      body: "Enterprise requests are evaluated based on your agency's size, integration requirements, and support needs. Allow business days for review. Status and effective limits appear in Settings → Enterprise after approval.",
    },
  ],
  sections: [
    {
      title: "Overview",
      paragraphs: [
        "Enterprise arrangements extend Professional and Business capabilities with negotiated limits, feature enablement, dedicated onboarding, and priority support. Enterprise customers typically manage large client portfolios, operate integration-heavy environments, or require compliance and branding configurations beyond standard plan tiers.",
        "Unlike self-serve plan upgrades through Stripe checkout, enterprise onboarding involves a review process. Once approved, plan overrides and support contacts are applied to your workspace and visible in Settings → Enterprise and Settings → Billing.",
        "Enterprise is designed for customer-facing outcomes: higher limits, tailored rollout, and direct support — not internal platform administration. All request, status, and override visibility flows through Settings → Enterprise and Settings → Billing within your workspace.",
      ],
    },
    {
      title: "Purpose",
      paragraphs: [
        "Standard plans serve most agencies well, but some organizations need higher API rate limits, expanded monitoring capacity, additional seats, custom feature combinations, or hands-on migration support. Enterprise exists to accommodate these requirements without forcing agencies into one-size-fits-all tiers.",
        "The enterprise program also provides a direct support channel and agreed response expectations, reducing operational risk for agencies running mission-critical client operations on the platform.",
        "Submitting an enterprise request is the first step. Include specific numbers — client count, seat needs, expected API volume, integration count — so the review team can evaluate your requirements efficiently and propose appropriate overrides.",
      ],
    },
    {
      title: "Core Concepts",
      bullets: [
        "Enterprise request — a formal inquiry submitted from Settings → Enterprise or Settings → Billing describing your requirements.",
        "Plan override — a custom configuration applied to your workspace after approval, adjusting limits or enabling features beyond your base tier.",
        "Custom onboarding — a structured rollout including workspace setup, migration planning, and team training.",
        "Priority support — expedited assistance through agreed channels with defined response expectations.",
        "Custom limits — negotiated caps on clients, seats, API rate limits, monitoring targets, automation runs, and other resources.",
        "Account contact — your designated Auroranexis point of contact for enterprise matters.",
      ],
    },
    {
      title: "Features",
      bullets: [
        "Custom client, seat, and portfolio limits for large agencies.",
        "Elevated API rate limits for integration-heavy deployments.",
        "Expanded monitoring, automation, and storage capacity.",
        "Feature enablement beyond standard plan tier boundaries.",
        "Dedicated onboarding with migration and rollout planning.",
        "Priority support with agreed response times.",
        "Flexible billing arrangements negotiated outside standard Stripe checkout where applicable.",
        "Plan override visibility in Settings → Enterprise.",
      ],
      subsections: [
        {
          title: "What enterprise includes",
          paragraphs: [
            "Enterprise customers receive a combination of custom limits, feature overrides, onboarding support, and priority assistance tailored to their operational profile. The specific package is defined during the review process and reflected in Settings → Enterprise after approval. Standard self-serve checkout cannot provision enterprise-level customizations — the request flow is required.",
          ],
        },
      ],
    },
    {
      title: "Step-by-step usage",
      subsections: [
        {
          title: "Submit an enterprise request",
          ordered: [
            "Open Settings → Enterprise or Settings → Billing.",
            "Select Request enterprise or the equivalent action.",
            "Provide your agency name, team size, client count, and integration requirements.",
            "Describe specific limits or features you need beyond your current plan.",
            "Submit the request and note the confirmation or reference shown.",
            "Monitor request status in Settings → Enterprise during the review period.",
          ],
        },
        {
          title: "Complete custom onboarding",
          ordered: [
            "After approval, your account contact schedules a kickoff call.",
            "Align workspace roles and permissions with your delivery model.",
            "Plan data migration, report templates, and portal rollout phases.",
            "Configure integrations and automation with agreed capacity limits.",
            "Complete check-in sessions to validate the rollout against your requirements.",
          ],
        },
        {
          title: "Verify plan overrides",
          ordered: [
            "Open Settings → Enterprise after approval.",
            "Review applied overrides for client limits, seats, API rate limits, and enabled features.",
            "Cross-reference effective limits in Settings → Usage.",
            "Contact your account contact if displayed limits do not match the approved agreement.",
          ],
        },
        {
          title: "Use priority support",
          ordered: [
            "Refer to the support contact details shared during onboarding.",
            "Use the agreed channel (email or support portal) for enterprise-priority requests.",
            "Include workspace name, issue description, and impact assessment in your request.",
            "Escalate through your account contact for urgent operational issues.",
          ],
        },
      ],
    },
    {
      title: "Best Practices",
      bullets: [
        "Document required limits and features before submitting your request — specific numbers accelerate review.",
        "Identify an internal operations owner who will manage the enterprise rollout and serve as the primary contact.",
        "Plan portal and integration rollouts in phases to avoid overwhelming client contacts during migration.",
        "Review Settings → Enterprise after approval to confirm overrides match your agreement.",
        "Maintain an up-to-date team roster in Settings → Team as your agency grows.",
        "Coordinate billing changes, renewals, or cancellations with your account contact rather than self-serve portal actions when under a negotiated agreement.",
        "Schedule periodic check-ins with your account contact to review usage trends and adjust limits proactively.",
        "Monitor Settings → Usage regularly to identify when approaching custom limits before operations are blocked.",
      ],
    },
    {
      title: "Examples",
      subsections: [
        {
          title: "Marketing agency",
          paragraphs: [
            "An agency operating four sub-brands needs white-label portal configurations beyond the Business tier client limit. They submit an enterprise request from Settings → Billing specifying brand count, portal customization needs, and seat requirements. Approved overrides increase client and portal limits, and onboarding includes branding configuration guidance for each sub-brand.",
          ],
        },
        {
          title: "AI automation agency",
          paragraphs: [
            "An automation agency with high-volume webhook and API traffic submits an enterprise request detailing expected automation runs, integration count, and incident write volume. After approval, custom automation and API limits appear in Settings → Enterprise. The team validates headroom in Settings → Usage before migrating production workflows from a staging workspace.",
          ],
        },
        {
          title: "MSP",
          paragraphs: [
            "An MSP with one hundred fifty clients and twelve integrations needs API rate limits five times the Business tier maximum. They submit an enterprise request from Settings → Enterprise detailing client count, integration list, and expected API call volume. After approval, custom API limits and expanded automation capacity appear in Settings → Enterprise. Priority support contact details are shared during onboarding.",
          ],
        },
        {
          title: "Consultancy",
          paragraphs: [
            "A boutique consultancy growing from forty to ninety clients within one year submits an enterprise request anticipating seat, client, and automation run requirements. Rather than repeatedly upgrading through self-serve checkout, they negotiate a single override package. After approval, limits in Settings → Enterprise accommodate projected growth with a scheduled check-in at the six-month mark.",
          ],
        },
        {
          title: "Enterprise deployment",
          paragraphs: [
            "A compliance-focused agency migrating three hundred client records requests enterprise onboarding with migration support. During custom onboarding, the team helps map report templates, configure role structures, and phase portal rollout over six weeks. Plan overrides enable compliance audit features and expanded storage for historical records.",
          ],
        },
      ],
    },
    {
      title: "Troubleshooting",
      table: {
        caption: "Common enterprise issues",
        headers: ["Problem", "Cause", "Solution"],
        rows: [
          [
            "Enterprise request still pending",
            "Review process requires business days for evaluation",
            "Check Settings → Enterprise for status updates; allow time before follow-up.",
          ],
          [
            "Limits not updated after approval",
            "Override application may still be in progress",
            "Confirm approval is complete in Settings → Enterprise; contact your account contact if overdue.",
          ],
          [
            "Cannot find enterprise contact details",
            "Contact information shared during onboarding email",
            "Refer to the onboarding email or open a standard support request referencing your enterprise status.",
          ],
          [
            "Self-serve checkout conflicts with enterprise agreement",
            "Plan changes through Stripe may not reflect negotiated terms",
            "Contact your account contact before making plan changes through the customer portal.",
          ],
          [
            "Feature not enabled despite override",
            "Some capabilities require additional configuration",
            "Verify the feature is listed in Settings → Enterprise and complete any setup steps in the relevant module.",
          ],
          [
            "Usage approaching custom limits",
            "Growth exceeded initial negotiated caps",
            "Monitor Settings → Usage and request a limit adjustment through your account contact before hitting caps.",
          ],
          [
            "Billing page shows different plan than enterprise agreement",
            "Display may reflect base tier with overrides applied separately",
            "Cross-reference Settings → Enterprise for override details; contact your account contact for billing questions.",
          ],
        ],
      },
    },
  ],
  faq: [
    {
      question: "How do I request an enterprise plan?",
      answer:
        "Open Settings → Enterprise or Settings → Billing and submit an enterprise request with your agency details and requirements. The Auroranexis team reviews scope, limits, and timeline before approval.",
    },
    {
      question: "Is enterprise an instant upgrade?",
      answer:
        "No. Enterprise is a reviewed process, not a self-serve checkout option. Allow business days for evaluation and onboarding scheduling.",
    },
    {
      question: "Where can I see my custom limits?",
      answer:
        "Approved plan overrides and effective limits are displayed in Settings → Enterprise. Cross-reference current consumption in Settings → Usage.",
    },
    {
      question: "Can I cancel an enterprise subscription through the customer portal?",
      answer:
        "Enterprise billing may follow a negotiated agreement. Coordinate cancellation or plan changes with your account contact to ensure contractual terms are respected.",
    },
    {
      question: "What support do enterprise customers receive?",
      answer:
        "Enterprise customers receive priority support through agreed channels with defined response expectations. Contact details are shared during onboarding.",
    },
    {
      question: "Do I need to be on Business before requesting Enterprise?",
      answer:
        "No specific tier is required. Submit your request from Settings → Enterprise with your current requirements regardless of your existing plan.",
    },
  ],
  relatedLinks: [
    { href: "/docs/billing", label: "Billing" },
    { href: "/docs/security", label: "Security" },
    { href: "/docs/getting-started", label: "Getting started" },
  ],
};
